package ar.edu.itba.ss.models;

import ar.edu.itba.ss.Particle;

import java.util.List;

public class Frame<T extends Particle> {

    double time;
    List<T> particles;

    //////////////// Autogenerated /////////////////

    public List<T> getParticles() {
        return particles;
    }

    public void setParticles(List<T> particles) {
        this.particles = particles;
    }

    public Frame<T> withParticles(List<T> particles) {
        setParticles(particles);
        return this;
    }

    public double getTime() {
        return time;
    }

    public void setTime(double time) {
        this.time = time;
    }

    public Frame<T> withTime(double time) {
        setTime(time);
        return this;
    }

    @Override
    public String toString() {
        return "Frame{" +
            "time=" + time +
            ", particles=" + particles +
            '}';
    }
}
