package ar.edu.itba.ss.models;

import java.util.List;

public class Frame {

    double time;
    List<ContractileParticle> particles;

    //////////////// Autogenerated /////////////////

    public List<ContractileParticle> getParticles() {
        return particles;
    }

    public void setParticles(List<ContractileParticle> particles) {
        this.particles = particles;
    }

    public Frame withParticles(List<ContractileParticle> particles) {
        setParticles(particles);
        return this;
    }

    public double getTime() {
        return time;
    }

    public void setTime(double time) {
        this.time = time;
    }

    public Frame withTime(double time) {
        setTime(time);
        return this;
    }

    @Override
    public String toString() {
        return "Frame{" +
            "time=" + time +
            ", particles=" + particles +
            '}';
    }
}
