package ar.edu.itba.ss;

import ar.edu.itba.ss.integrations.Integration;
import ar.edu.itba.ss.models.AcceleratedParticle;
import ar.edu.itba.ss.models.Frame;

import java.util.List;

public class MarsSimulation implements Simulation<List<Frame>> {

    // Status bar
    private final   int                     STATUS_BAR_SIZE         = 31;

    private         Integration                 integration;
    private         long                        gridSide;
    private         boolean                     statusBarActivated;

    // Stop conditions

    public List simulate() {
        return null;
    }

    //////////////// Autogenerated /////////////////

    public Integration getIntegration() {
        return integration;
    }
    public void setIntegration(Integration integration) {
        this.integration = integration;
    }
    public MarsSimulation withIntegration(Integration integration) {
        setIntegration(integration);
        return this;
    }

    public long getGridSide() {
        return gridSide;
    }
    public void setGridSide(long gridSide) {
        this.gridSide = gridSide;
    }
    public MarsSimulation withGridSide(long gridSide) {
        setGridSide(gridSide);
        return this;
    }

    public boolean isStatusBarActivated() {
        return statusBarActivated;
    }
    public void setStatusBarActivated(boolean statusBarActivated) {
        this.statusBarActivated = statusBarActivated;
    }
    public MarsSimulation withStatusBarActivated(boolean statusBarActivated) {
        setStatusBarActivated(statusBarActivated);
        return this;
    }
}
