package ar.edu.itba.ss;

import ar.edu.itba.ss.models.AcceleratedParticle;
import ar.edu.itba.ss.models.Frame;

import java.util.List;

public class MarsSimulation implements Simulation<List<Frame>> {

    // Status bar
    private final   int                     STATUS_BAR_SIZE         = 31;

    private         List<AcceleratedParticle>  particles;
    private         long                    gridSide;
    private         boolean                 statusBarActivated;

    // Stop conditions

    public List simulate() {
        return null;
    }

    //////////////// Autogenerated /////////////////

    public List<AcceleratedParticle> getParticles() {
        return particles;
    }
    public void setParticles(List<AcceleratedParticle> particles) {
        this.particles = particles;
    }
    public MarsSimulation withParticles(List<AcceleratedParticle> particles) {
        setParticles(particles);
        return this;
    }

    public long getGridSide() {
        return gridSide;
    }
    public void setGridSide(long gridSide) {
        this.gridSide = gridSide;
    }
    public MarsSimulation withGridSide(long gridSide) {
        setGridSide(gridSide);
        return this;
    }

    public boolean isStatusBarActivated() {
        return statusBarActivated;
    }
    public void setStatusBarActivated(boolean statusBarActivated) {
        this.statusBarActivated = statusBarActivated;
    }
    public MarsSimulation withStatusBarActivated(boolean statusBarActivated) {
        setStatusBarActivated(statusBarActivated);
        return this;
    }
}
