package ar.edu.itba.ss;

import ar.edu.itba.ss.integrations.Integration;
import ar.edu.itba.ss.integrations.VerletOriginal;
import ar.edu.itba.ss.models.AcceleratedParticle;
import ar.edu.itba.ss.models.Frame;
import ar.edu.itba.ss.models.ParticleType;

import java.util.*;

public class OscillatorSimulation implements Simulation<List<Frame>> {

    // Status bar
    private final   int                     STATUS_BAR_SIZE         = 31;

    private         Integration             integration;
    private         double                  dt;
    private         double                  maxTime;
    private         long                    saveFactor;
    private         boolean                 statusBarActivated;

    private         AcceleratedParticle     particle;

    // Stop conditions

    public List<Frame> simulate() {

        // Initial Conditions
        double k        = Math.pow(10,4);       // N/m
        double r        = 1;                    // m
        double gamma    = 100;                  // kg/s
        double vy       = -gamma/2;             // m/s

        particle = new AcceleratedParticle()
            .withType(ParticleType.OSCILLABLE)
            .withY(r)
            .withVy(vy)
            .withMass(70)                   // kg
            ;


        List<Frame> frames = new ArrayList<>();

        AcceleratedParticle previousParticle = particle;                    // (t-dt)
        AcceleratedParticle currentParticle = previousParticle.clone();     // (t)
        currentParticle.setY(2 * currentParticle.getY() - previousParticle.getY()+ (Math.pow(dt,2)/currentParticle.getMass())*currentParticle.getForceY()); // ry(t) // TODO: Change
        AcceleratedParticle nextParticle;                                   // (t+dt)

        double currentForce;

        frames.add(new Frame()
            .withParticles(Collections.singletonList(previousParticle))
            .withTime(0)
        );

        for (double time = dt; time < maxTime; time += dt) {   // currentTime
            if (statusBarActivated) Utils.printLoadingBar(time/maxTime, STATUS_BAR_SIZE);

            currentForce = - k * currentParticle.getY() - gamma * currentParticle.getVy();  // f(t) = -k*r - gamma*r'
            currentParticle.setForceY(currentForce);

            nextParticle = integration.update(currentParticle, previousParticle, dt);       //updated particle with ri(t+dt) y vi(t)

            frames.add(new Frame()
                .withParticles(Collections.singletonList(currentParticle))
                .withTime(time)
            );

            previousParticle = currentParticle;
            currentParticle  = nextParticle;
        }

        return frames;
    }

    //////////////// Autogenerated /////////////////


    public Integration getIntegration() {
        return integration;
    }
    public void setIntegration(Integration integration) {
        this.integration = integration;
    }
    public OscillatorSimulation withIntegration(Integration integration) {
        setIntegration(integration);
        return this;
    }

    public double getDt() {
        return dt;
    }
    public void setDt(double dt) {
        this.dt = dt;
    }
    public OscillatorSimulation withDt(double dt) {
        setDt(dt);
        return this;
    }

    public double getMaxTime() {
        return maxTime;
    }
    public void setMaxTime(double maxTime) {
        this.maxTime = maxTime;
    }
    public OscillatorSimulation withMaxTime(double maxTime) {
        setMaxTime(maxTime);
        return this;
    }

    public long getSaveFactor() {
        return saveFactor;
    }
    public void setSaveFactor(long saveFactor) {
        this.saveFactor = saveFactor;
    }
    public OscillatorSimulation withSaveFactor(long saveFactor) {
        setSaveFactor(saveFactor);
        return this;
    }

    public boolean isStatusBarActivated() {
        return statusBarActivated;
    }
    public void setStatusBarActivated(boolean statusBarActivated) {
        this.statusBarActivated = statusBarActivated;
    }
    public OscillatorSimulation withStatusBarActivated(boolean statusBarActivated) {
        setStatusBarActivated(statusBarActivated);
        return this;
    }
}
