package ar.edu.itba.ss.models;

import java.util.List;

public class Frame {

    double time;
    List<VelocityParticle> particles;

    //////////////// Autogenerated /////////////////

    public List<VelocityParticle> getParticles() {
        return particles;
    }

    public void setParticles(List<VelocityParticle> particles) {
        this.particles = particles;
    }

    public Frame withParticles(List<VelocityParticle> particles) {
        setParticles(particles);
        return this;
    }

    public double getTime() {
        return time;
    }

    public void setTime(double time) {
        this.time = time;
    }

    public Frame withTime(long time) {
        setTime(time);
        return this;
    }

}
