package ar.edu.itba.ss.models;

public class ParticleHistory {
    private     AcceleratedParticle past;
    private     AcceleratedParticle present;
    private     AcceleratedParticle future;

    // Autogenerated //

    public AcceleratedParticle getPast() {
        return past;
    }
    public void setPast(AcceleratedParticle past) {
        this.past = past;
    }
    public ParticleHistory withPast(AcceleratedParticle past) {
        setPast(past);
        return this;
    }

    public AcceleratedParticle getPresent() {
        return present;
    }
    public void setPresent(AcceleratedParticle present) {
        this.present = present;
    }
    public ParticleHistory withPresent(AcceleratedParticle present) {
        setPresent(present);
        return this;
    }

    public AcceleratedParticle getFuture() {
        return future;
    }
    public void setFuture(AcceleratedParticle future) {
        this.future = future;
    }
    public ParticleHistory withFuture(AcceleratedParticle future) {
        setFuture(future);
        return this;
    }
}
