package ar.edu.itba.ss.algorithms;

import ar.edu.itba.ss.Utils;
import ar.edu.itba.ss.models.ContractileParticle;
import ar.edu.itba.ss.models.EscapeRoomSimulationResult;
import ar.edu.itba.ss.models.Frame;

import java.util.*;
import java.util.stream.Collectors;

public abstract class EscapeRoomSimulation {

    // Status bar
    protected final int                         STATUS_BAR_SIZE         = 31;

    protected       double                      dt;
    protected       double                      maxTime;
    protected       long                        saveFactor;
    protected       boolean                     statusBarActivated;

    protected       Random                      random;
    protected       double                      minRadius;
    protected       double                      maxRadius;
    protected       double                      escapeSpeed;
    protected       double                      maxDesiredSpeed;
    protected       double                      beta;
    protected       double                      tau;
    protected       double                      roomWidth;
    protected       double                      roomHeight;
    protected       double                      targetWidth;
    protected       double                      outerTargetDistance;
    protected       double                      outerTargetWidth;
    protected       List<ContractileParticle>   particles;

    public boolean stop(List<ContractileParticle> particles) {
        return particles.stream().allMatch(particle -> (particle.getY() + particle.getRadius()) < 0);
    }

    public void printStatusBar(double time) {
        if (statusBarActivated) Utils.printLoadingBar(time/maxTime, STATUS_BAR_SIZE);
    }

    public abstract ContractileParticle getNextParticle(ContractileParticle particle, List<ContractileParticle> otherParticles);

    public EscapeRoomSimulationResult simulate() {

        List<ContractileParticle> currentParticles = particles;
        List<ContractileParticle> nextParticles    = new LinkedList<>();
        List<ContractileParticle> aux;

        final List<Frame<ContractileParticle>> frames = new LinkedList<>();
        final Map<Long, Double> escapeTimes           = new HashMap<>();

        long count;
        double time;

        for (time = 0, count = 0; time <= maxTime && !stop(currentParticles); time += dt, count++) {
            // Status bar
            printStatusBar(time);

            // Save particles
            if (count % saveFactor == 0) {
                frames.add(new Frame<ContractileParticle>()
                    .withParticles(currentParticles.stream()
                        .map(ContractileParticle::clone)
                        .collect(Collectors.toList())
                    )
                    .withTime(time)
                );
            }

            // Update particles
            for (int i = 0; i < currentParticles.size(); i++) {
                ContractileParticle particle = currentParticles.get(i);
                ContractileParticle nextParticle = getNextParticle(particle, currentParticles.stream().filter(other -> other != particle).collect(Collectors.toList()));

                nextParticles.add(nextParticle);
                if ((particle.getY() + particle.getRadius()) >= 0 && (nextParticle.getY() + nextParticle.getRadius()) < 0 && !escapeTimes.containsKey(particle.getId())) {
                    escapeTimes.put(particle.getId(), time);
                }
            }

            aux = currentParticles;
            currentParticles = nextParticles;
            nextParticles = aux;
            nextParticles.clear();
        }

        // Status bar
        printStatusBar(maxTime+0.01);
        System.out.println();

        return new EscapeRoomSimulationResult()
            .withSimulationUsed(this)
            .withFrames(frames)
            .withEscapeTimes(new LinkedList<>(escapeTimes.values()))
            ;
    }

    //////////////// Autogenerated /////////////////

    public Random getRandom() {
        return random;
    }
    public void setRandom(Random random) {
        this.random = random;
    }
    public EscapeRoomSimulation withRandom(Random random) {
        setRandom(random);
        return this;
    }

    public double getDt() {
        return dt;
    }
    public void setDt(double dt) {
        this.dt = dt;
    }
    public EscapeRoomSimulation withDt(double dt) {
        setDt(dt);
        return this;
    }

    public double getMaxTime() {
        return maxTime;
    }
    public void setMaxTime(double maxTime) {
        this.maxTime = maxTime;
    }
    public EscapeRoomSimulation withMaxTime(double maxTime) {
        setMaxTime(maxTime);
        return this;
    }

    public long getSaveFactor() {
        return saveFactor;
    }
    public void setSaveFactor(long saveFactor) {
        this.saveFactor = saveFactor;
    }
    public EscapeRoomSimulation withSaveFactor(long saveFactor) {
        setSaveFactor(saveFactor);
        return this;
    }

    public boolean isStatusBarActivated() {
        return statusBarActivated;
    }
    public void setStatusBarActivated(boolean statusBarActivated) {
        this.statusBarActivated = statusBarActivated;
    }
    public EscapeRoomSimulation withStatusBarActivated(boolean statusBarActivated) {
        setStatusBarActivated(statusBarActivated);
        return this;
    }

    public double getRoomWidth() {
        return roomWidth;
    }
    public void setRoomWidth(double roomWidth) {
        this.roomWidth = roomWidth;
    }
    public EscapeRoomSimulation withRoomWidth(double roomWidth) {
        setRoomWidth(roomWidth);
        return this;
    }

    public double getRoomHeight() {
        return roomHeight;
    }
    public void setRoomHeight(double roomHeight) {
        this.roomHeight = roomHeight;
    }
    public EscapeRoomSimulation withRoomHeight(double roomHeight) {
        setRoomHeight(roomHeight);
        return this;
    }

    public double getTargetWidth() {
        return targetWidth;
    }
    public void setTargetWidth(double targetWidth) {
        this.targetWidth = targetWidth;
    }
    public EscapeRoomSimulation withTargetWidth(double targetWidth) {
        setTargetWidth(targetWidth);
        return this;
    }

    public double getOuterTargetDistance() {
        return outerTargetDistance;
    }
    public void setOuterTargetDistance(double outerTargetDistance) {
        this.outerTargetDistance = outerTargetDistance;
    }
    public EscapeRoomSimulation withOuterTargetDistance(double outerTargetDistance) {
        setOuterTargetDistance(outerTargetDistance);
        return this;
    }

    public double getOuterTargetWidth() {
        return outerTargetWidth;
    }
    public void setOuterTargetWidth(double outerTargetWidth) {
        this.outerTargetWidth = outerTargetWidth;
    }
    public EscapeRoomSimulation withOuterTargetWidth(double outerTargetWidth) {
        setOuterTargetWidth(outerTargetWidth);
        return this;
    }

    public Double getMinRadius() {
        return minRadius;
    }
    public void setMinRadius(Double minRadius) {
        this.minRadius = minRadius;
    }
    public EscapeRoomSimulation withMinRadius(Double minRadius) {
        setMinRadius(minRadius);
        return this;
    }

    public Double getMaxRadius() {
        return maxRadius;
    }
    public void setMaxRadius(Double maxRadius) {
        this.maxRadius = maxRadius;
    }
    public EscapeRoomSimulation withMaxRadius(Double maxRadius) {
        setMaxRadius(maxRadius);
        return this;
    }

    public Double getBeta() {
        return beta;
    }
    public void setBeta(Double beta) {
        this.beta = beta;
    }
    public EscapeRoomSimulation withBeta(Double beta) {
        setBeta(beta);
        return this;
    }

    public Double getTau() {
        return tau;
    }
    public void setTau(Double tau) {
        this.tau = tau;
    }
    public EscapeRoomSimulation withTau(Double tau) {
        setTau(tau);
        return this;
    }

    public Double getEscapeSpeed() {
        return escapeSpeed;
    }
    public void setEscapeSpeed(Double escapeSpeed) {
        this.escapeSpeed = escapeSpeed;
    }
    public EscapeRoomSimulation withEscapeSpeed(Double escapeSpeed) {
        setEscapeSpeed(escapeSpeed);
        return this;
    }

    public Double getMaxDesiredSpeed() {
        return maxDesiredSpeed;
    }
    public void setMaxDesiredSpeed(Double maxDesiredSpeed) {
        this.maxDesiredSpeed = maxDesiredSpeed;
    }
    public EscapeRoomSimulation withMaxDesiredSpeed(Double maxDesiredSpeed) {
        setMaxDesiredSpeed(maxDesiredSpeed);
        return this;
    }

    public List<ContractileParticle> getParticles() {
        return particles;
    }
    public void setParticles(List<ContractileParticle> particles) {
        this.particles = particles;
    }
    public EscapeRoomSimulation withParticles(List<ContractileParticle> particles) {
        setParticles(particles);
        return this;
    }
}
