package ar.edu.itba.ss.dto;

import ar.edu.itba.ss.models.EscapeRoomSimulationResult;

public class ExtendedEscapeSimulationsResult extends EscapeRoomSimulationResult {
    private double seed;
    private long numberOfParticles;

    //////////////// Autogenerated /////////////////

    public static ExtendedEscapeSimulationsResult extendResult(final EscapeRoomSimulationResult result) {
        ExtendedEscapeSimulationsResult ret = new ExtendedEscapeSimulationsResult();
        ret.setDt                 (result.getDt());
        ret.setRoomWidth          (result.getRoomWidth());
        ret.setRoomHeight         (result.getRoomHeight());
        ret.setTargetWidth        (result.getTargetWidth());
        ret.setOuterTargetDistance(result.getOuterTargetDistance());
        ret.setOuterTargetWidth   (result.getOuterTargetWidth());
        ret.setMinRadius          (result.getMinRadius());
        ret.setMaxRadius          (result.getMaxRadius());
        ret.setBeta               (result.getBeta());
        ret.setTau                (result.getTau());
        ret.setEscapeSpeed        (result.getEscapeSpeed());
        ret.setMaxDesiredSpeed    (result.getMaxDesiredSpeed());
        return ret;
    }

    public double getSeed() {
        return seed;
    }
    public void setSeed(double seed) {
        this.seed = seed;
    }
    public ExtendedEscapeSimulationsResult withSeed(double seed) {
        setSeed(seed);
        return this;
    }

    public long getNumberOfParticles() {
        return numberOfParticles;
    }
    public void setNumberOfParticles(long numberOfParticles) {
        this.numberOfParticles = numberOfParticles;
    }
    public ExtendedEscapeSimulationsResult withNumberOfParticles(long numberOfParticles) {
        setNumberOfParticles(numberOfParticles);
        return this;
    }
}
